### ISSUE TITLE
How to download GW170817-IMRD_data0_1187008882-43_generation_data_dump.pickle_H1_psd.txt.

### ISSUE THREAD

**Issue by zsdnr** [ThibeauWouters/TurboPE-BNS#3]
Hello, I am very interested in this project and I would like to ask where to obtain GW170817-IMRD_data0_1187008882-43_generation_data_dump.pickle_H1_psd.txt. I couldn't find the download address on the GWOSC website . Look forward to your reply，thank you.

**Comment by ThibeauWouters** [comment]
Hi,

Thanks a lot for reading the paper and going through our Github repo! 

I have just added the datasets used in the analysis of the real events to the Zenodo. You can find the new data [here](https://zenodo.org/records/12628144), with the required data as well as PSDs located in `GW170817_data.zip` and `GW190425_data.zip` files. 

Please let me know if I can help with anything else!
